### Do not edit this file

## This is a single workflow for understanding the app that uses LangGraph to manage the state of the conversation and call the ChatGroq model for question-answering tasks. It also uses Chroma as a vector store to retrieve relevant context from a PDF document.

import sys
from pathlib import Path
import shutil

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# from annotated_types import doc
from fastapi import FastAPI
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from config import settings
import os
import numpy as np
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
import pandas as pd
import tempfile
from langgraph.checkpoint.memory import InMemorySaver, MemorySaver
from langgraph.graph import START, MessagesState, StateGraph

app = FastAPI()

def get_resume_path() -> Path:
    return (Path(__file__).resolve().parent / "data" / "Karmilan_Software_Engineer_Resume.pdf").resolve()


loader = PyPDFLoader(str(get_resume_path()))
pdf_pages = loader.load()

all_minilm_embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2",
)
# multilingual_embedding = HuggingFaceEmbeddings(
#     model_name="intfloat/multilingual-e5-large",
# )

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)
chunked_doc = text_splitter.split_documents(pdf_pages)

persistent_directory = tempfile.mkdtemp(prefix="chroma_db_")

vectordb = Chroma.from_documents(
    documents=chunked_doc,
    embedding=all_minilm_embeddings,
    persist_directory=persistent_directory,
)


# Groq
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = settings.groq_api_key

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    max_tokens=250,
    # reasoning_format="parsed",
)

# print(llm.invoke("write apoem about jaffna"))

# Initialize the ChatGroq model
def get_chat_model():
    """Caches the ChatGroq model."""
    return ChatGroq(
        model="llama-3.1-8b-instant",
        temperature=0,
        max_tokens=250,
    )

model = get_chat_model()


# Memory

def call_model(state: MessagesState):
    system_prompt = (
        "You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question."
        "If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise."
        "Answer all questions to the best of your ability."
    )
    messages = [SystemMessage(content=system_prompt)] + state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}

# Build and compile the LangGraph workflow
def get_langgraph_app():
    """Caches and compiles the LangGraph workflow."""
    workflow = StateGraph(state_schema=MessagesState)
    workflow.add_node("model", call_model)
    workflow.add_edge(START, "model")

    memory = MemorySaver()
    compiled_workflow = workflow.compile(checkpointer=memory)
    return compiled_workflow

compiled_workflow = get_langgraph_app()



@app.post("/ask")
def ask_question(question: str):
    docs = vectordb.similarity_search_with_score(question, k=2)

    _docs = pd.DataFrame(
        [
            (
                question,
                doc[0].page_content,
                doc[0].metadata.get('source'),
                doc[1],
            )
            for doc in docs
        ],
        columns=['query', 'paragraph', 'document', 'relevant_score'],
    )

    context = "\n\n".join(_docs['paragraph'])

    human_message = [HumanMessage(content=context + question)]

    response = compiled_workflow.invoke({"messages": human_message}, config={"configurable": {"thread_id": "1"}})

    return {"response": response}



#### optimized flow app.py ###

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fastapi import FastAPI
from pydantic import BaseModel
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from config import settings
import os
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
import pandas as pd
import tempfile
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import START, MessagesState, StateGraph

app = FastAPI()

def get_resume_path() -> Path:
    return (Path(__file__).resolve().parent / "data" / "Karmilan_Software_Engineer_Resume.pdf").resolve()


loader = PyPDFLoader(str(get_resume_path()))
pdf_pages = loader.load()

all_minilm_embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2",
)

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)
chunked_doc = text_splitter.split_documents(pdf_pages)

persistent_directory = tempfile.mkdtemp(prefix="chroma_db_")

vectordb = Chroma.from_documents(
    documents=chunked_doc,
    embedding=all_minilm_embeddings,
    persist_directory=persistent_directory,
)


# Groq

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = settings.groq_api_key

# Initialize the ChatGroq model

def get_chat_model():
    """Caches the ChatGroq model."""
    return ChatGroq(
        model="llama-3.1-8b-instant",
        temperature=0,
        max_tokens=250,
    )

model = get_chat_model()


# Memory

def call_model(state: MessagesState):
    system_prompt = (
        "You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question."
        "If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise."
        "Answer all questions to the best of your ability."
    )
    messages = [SystemMessage(content=system_prompt)] + state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}

# Build and compile the LangGraph workflow
def get_langgraph_app():
    """Caches and compiles the LangGraph workflow."""
    workflow = StateGraph(state_schema=MessagesState)
    workflow.add_node("model", call_model)
    workflow.add_edge(START, "model")

    memory = MemorySaver()
    compiled_workflow = workflow.compile(checkpointer=memory)
    return compiled_workflow

compiled_workflow = get_langgraph_app()

class AskRequest(BaseModel):
    question: str
    session_id: str = "default"



@app.post("/ask")
def ask_question(request: AskRequest):
    question = request.question
    docs = vectordb.similarity_search_with_score(question, k=2)

    _docs = pd.DataFrame(
        [
            (
                question,
                doc[0].page_content,
                doc[0].metadata.get('source'),
                doc[1],
            )
            for doc in docs
        ],
        columns=['query', 'paragraph', 'document', 'relevant_score'],
    )

    context = "\n\n".join(_docs['paragraph'])

    human_message = [
        HumanMessage(content=f"Context:\n{context}\n\nQuestion:\n{question}")
    ]

    response = compiled_workflow.invoke(
        {"messages": human_message},
        config={"configurable": {"thread_id": request.session_id}},
    )
    
    return {"response": response}